# -*- coding: utf-8 -*-
"""Model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ee8CkEd89iwef__DcKRc5AceniF-UZdn
"""

import pandas as pd

df = pd.read_csv('/content/Salary Data.csv')
df

df.isnull().sum()

for column in df.columns:
    if df[column].dtype in ['int64', 'float64']:
        df[column].fillna(df[column].mean(), inplace=True)
    else:
        df[column].fillna(df[column].mode()[0], inplace=True)
df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
for column in ['Gender', 'Education Level', 'Job Title']:
    df[column] = label_encoder.fit_transform(df[column])
display(df.head())

X = df.drop('Salary', axis=1)
y = df['Salary']

print("Input features (X) head:")
display(X.head())
print("\nTarget variable (y) head:")
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""## Model Training and Evaluation"""

from sklearn.metrics import mean_absolute_error, r2_score

# Dictionary to store model results
model_results = {}

"""### 1. Linear Regression"""

from sklearn.linear_model import LinearRegression

# Initialize and train the model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_lr = linear_reg_model.predict(X_test)

# Evaluate the model
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

model_results['Linear Regression'] = {'MAE': mae_lr, 'R2': r2_lr}

print(f"Linear Regression MAE: {mae_lr:.2f}")
print(f"Linear Regression R-squared: {r2_lr:.2f}")

"""### 2. Support Vector Machine (SVR)"""

from sklearn.svm import SVR

# Initialize and train the model
# SVR can be sensitive to scaling, but we'll use default for now
svr_model = SVR()
svr_model.fit(X_train, y_train)

# Make predictions
y_pred_svr = svr_model.predict(X_test)

# Evaluate the model
mae_svr = mean_absolute_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)

model_results['SVR'] = {'MAE': mae_svr, 'R2': r2_svr}

print(f"SVR MAE: {mae_svr:.2f}")
print(f"SVR R-squared: {r2_svr:.2f}")

"""### 3. K-Nearest Neighbors (KNN) Regressor"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the model
knn_model = KNeighborsRegressor(n_neighbors=5) # Using 5 neighbors as a default
knn_model.fit(X_train, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

model_results['KNN Regressor'] = {'MAE': mae_knn, 'R2': r2_knn}

print(f"KNN Regressor MAE: {mae_knn:.2f}")
print(f"KNN Regressor R-squared: {r2_knn:.2f}")

"""### 4. Decision Tree Regressor"""

from sklearn.tree import DecisionTreeRegressor

# Initialize and train the model
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

# Make predictions
y_pred_dt = dt_model.predict(X_test)

# Evaluate the model
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

model_results['Decision Tree'] = {'MAE': mae_dt, 'R2': r2_dt}

print(f"Decision Tree Regressor MAE: {mae_dt:.2f}")
print(f"Decision Tree Regressor R-squared: {r2_dt:.2f}")

"""### 5. Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

# Initialize and train the model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42) # Using 100 estimators as a default
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

model_results['Random Forest'] = {'MAE': mae_rf, 'R2': r2_rf}

print(f"Random Forest Regressor MAE: {mae_rf:.2f}")
print(f"Random Forest Regressor R-squared: {r2_rf:.2f}")

"""### Summary of Model Results"""

import pandas as pd

results_df = pd.DataFrame.from_dict(model_results, orient='index')
display(results_df.sort_values(by='R2', ascending=False))

import pickle
from google.colab import files

# Assuming rf_model is the best performing model
# (from the `model_results` table, Random Forest has the highest R2 and lowest MAE)
best_model = rf_model

# Define the filename
model_filename = 'best_model.pkl'

# Save the model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Model saved to {model_filename}")

# Provide a download link
files.download(model_filename)

import matplotlib.pyplot as plt
import seaborn as sns

results_df_reset = results_df.reset_index().rename(columns={'index': 'Model'})

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot MAE
sns.barplot(x='Model', y='MAE', data=results_df_reset.sort_values(by='MAE', ascending=True), ax=axes[0], palette='viridis', hue='Model', legend=False)
axes[0].set_title('Model Comparison: Mean Absolute Error (MAE)')
axes[0].set_ylabel('MAE')
axes[0].tick_params(axis='x', rotation=45)

# Plot R2 Score
sns.barplot(x='Model', y='R2', data=results_df_reset.sort_values(by='R2', ascending=False), ax=axes[1], palette='magma', hue='Model', legend=False)
axes[1].set_title('Model Comparison: R-squared (R2) Score')
axes[1].set_ylabel('R2 Score')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

